### PR TITLE
Add myself in `crates/teloxide-macros`

### PR DESCRIPTION
**Pull request by TheAwiteb**

### CODE REVIEW

**Review by WaffleLapkin — CHANGES_REQUESTED** [review]
no

**Comment by TheAwiteb** [comment]
> no

Why?

**Comment by WaffleLapkin** [comment]
r? WaffleLapkin

**Review by WaffleLapkin — CHANGES_REQUESTED** [review]
a

**Comment by TheAwiteb** [comment]
@teloxidebot ready

**Review by WaffleLapkin — COMMENTED** [review]
d

**Pull request closed without merging**
